version: '3.8'

services:
  # Database Service
  db:
    image: postgres:15-alpine
    container_name: mca_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mca_db
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d mca_db" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - mca_network

  # Backend Service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: mca_backend
    volumes:
      - ./backend:/app
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/mca_db
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - mca_network
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  # Frontend Service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: mca_frontend
    environment:
      - NEXT_PUBLIC_API_URL=http://apimca.moibluu.com:8000
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - mca_network

volumes:
  postgres_data:


networks:
  mca_network:
    driver: bridge
